exports.deployContract = require("./deploy_fundMe")
exports.interactContract = require("./fundMe_fund")
exports.checknft = require("./check_nft")
exports.mintnft = require("./mint-nft")
exports.lockAndCross = require("./lock-and-cross")
exports.checkwnft = require("./check_wnft")
