// SPDX-License-Identifier: MIT
// Compatible with OpenZeppelin Contracts ^5.4.0
pragma solidity ^0.8.27;

import {ERC721} from "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import {ERC721Enumerable} from "@openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol";
import {ERC721URIStorage} from "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";
import {AutomationCompatibleInterface} from "@chainlink/contracts/src/v0.8/automation/AutomationCompatible.sol";


contract Flower is ERC721, ERC721Enumerable, ERC721URIStorage, Ownable, AutomationCompatibleInterface {
    uint256 private _nextTokenId;
    uint256 public interval;
    uint256 public lastTimeStamp;

    string[] IpfsUrl = [
        "ipfs://QmYt7Vt3fgvQhuQJSGwa4XaKYmovzPxFomBf7anoH8KvKQ",
        "ipfs://Qmcs98BAPaa5nVdrkHCqxVK19U3pqGM3NtfYXo1ojnKxaP",
        "ipfs://QmQvBnT5u9A1icTN2hqd2PbHMQ23U746dta95zPP1fQWP8"
        ];


    constructor(address initialOwner, uint256 _interval)
        ERC721("Flower", "FLW")
        Ownable(initialOwner)
    {
        interval = _interval;
        lastTimeStamp = block.timestamp;
    }

    function safeMint()
        public
        onlyOwner
        returns (uint256)
    {
        uint256 tokenId = _nextTokenId++;
        _safeMint(msg.sender, tokenId);
        _setTokenURI(tokenId, IpfsUrl[0]);
        return tokenId;
    }

    // The following functions are overrides required by Solidity.

    function _update(address to, uint256 tokenId, address auth)
        internal
        override(ERC721, ERC721Enumerable)
        returns (address)
    {
        return super._update(to, tokenId, auth);
    }

    function _increaseBalance(address account, uint128 value)
        internal
        override(ERC721, ERC721Enumerable)
    {
        super._increaseBalance(account, value);
    }

    function tokenURI(uint256 tokenId)
        public
        view
        override(ERC721, ERC721URIStorage)
        returns (string memory)
    {
        return super.tokenURI(tokenId);
    }

    function supportsInterface(bytes4 interfaceId)
        public
        view
        override(ERC721, ERC721Enumerable, ERC721URIStorage)
        returns (bool)
    {
        return super.supportsInterface(interfaceId);
    }

    function checkUpkeep(
        bytes calldata /* checkData */
    )
        external
        view
        override
        returns (bool upkeepNeeded, bytes memory /* performData */)
    {
        upkeepNeeded = (block.timestamp - lastTimeStamp) > interval;
        // We don't use the checkData in this example. The checkData is defined when the Upkeep was registered.
    }

    function performUpkeep(bytes calldata /* performData */) external override {
        if ((block.timestamp - lastTimeStamp) > interval) {
            lastTimeStamp = block.timestamp;
            if (keccak256(abi.encodePacked(tokenURI(0))) == keccak256(abi.encodePacked(IpfsUrl[0]))) {
                _setTokenURI(0, IpfsUrl[1]);
            } else if (keccak256(abi.encodePacked(tokenURI(0))) == keccak256(abi.encodePacked(IpfsUrl[1]))) {
                _setTokenURI(0, IpfsUrl[2]);
            } else {
                _setTokenURI(0, IpfsUrl[0]);
            }
        }
        // We don't use the performData in this example. The performData is generated by the Automation Node's call to your checkUpkeep function
    }
}
